// Write a function that takes a 6 digit number as input 
// and prints all 5 digits number 
// where 5 digit is generated by taking average of 2 digits at a time

function printAll5DigitsNum(num) {
    let arrOfNums = String(num).split("");
  
    for (let i = 0; i < arrOfNums.length - 1; i++) 
    {
      let leftSide = arrOfNums.slice(0, i);
      let avgNum = Math.floor(
        (Number(arrOfNums[i]) + Number(arrOfNums[i + 1])) / 2
      );
      let rightSide = arrOfNums.slice(i + 2);
  
      let newNum = 0;
      leftSide.forEach((digit, index) => {
        if (index === 0) {
          newNum = digit;
        } else {
          newNum += digit;
        }
      });
      newNum += avgNum;
      rightSide.forEach((digit) => {
        newNum += digit;
      });
      
      console.log(Number(newNum))
    }
  }
  
  printAll5DigitsNum(923828);
  
  // Math.floor(9+2)/2  3 8 2 8 = 5 3 8 2 8
  // 9 Math.floor(2+3)/2 8 2 8  = 9 2 8 2 8
  // 9 2 Math.floor(3+8)/2 2 8  = 9 2 5 2 8
  // 9 2 3 Math.floor(8+2)/2 8  = 9 2 3 5 8
  // 9 2 3 8 Math.floor(2+8)/2  = 9 2 3 8 5